#REQUIRED OPTIONS
JOBID: "snake_split_bin_test"
REFIN: "/mnt/lustre/groups/biol-chong-2019/development/MAGqual/canu10_med.fasta"
BIN_LOC: "/mnt/lustre/groups/biol-chong-2019/development/MAGqual/clusters/"
#OPTIONAL
checkm_db: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
bakta_db: ""
